In [ ]:
import numpy as np

In [ ]:
km = np.loadtxt('carros-km.txt')

In [ ]:
km

array([4.44100e+04, 5.71200e+03, 3.71230e+04, 0.00000e+00, 2.57570e+04,
       1.07280e+04, 0.00000e+00, 7.75990e+04, 9.91970e+04, 3.79780e+04,
       1.28590e+04, 8.05200e+03, 8.97730e+04, 0.00000e+00, 4.14570e+04,
       1.15607e+05, 4.64490e+04, 0.00000e+00, 3.70860e+04, 1.51730e+04,
       1.01193e+05, 0.00000e+00, 9.80790e+04, 1.02959e+05, 0.00000e+00,
       0.00000e+00, 5.79500e+03, 0.00000e+00, 5.88480e+04, 9.43810e+04,
       3.01630e+04, 5.33320e+04, 1.77200e+04, 3.38080e+04, 9.06840e+04,
       4.39750e+04, 0.00000e+00, 0.00000e+00, 5.52600e+03, 0.00000e+00,
       9.34150e+04, 4.07620e+04, 0.00000e+00, 8.63020e+04, 0.00000e+00,
       9.75500e+03, 6.99450e+04, 2.39500e+03, 0.00000e+00, 8.03490e+04,
       8.55540e+04, 5.04960e+04, 6.77160e+04, 9.39470e+04, 3.53450e+04,
       8.10070e+04, 1.19513e+05, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 1.18895e+05, 4.85090e+04, 1.00912e+05,
       9.56490e+04, 0.00000e+00, 9.04950e+04, 0.00000e+00, 2.913

In [ ]:
anos = np.loadtxt('carros-km.txt', dtype = int)
anos

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [ ]:
anos

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [ ]:
km_media = km / (2019 - anos)

In [ ]:
km_media

array([-1.04762803, -1.54670999, -1.05751481,  0.        , -1.0850535 ,
       -1.23182914,  0.        , -1.02671342, -1.02077631, -1.05614728,
       -1.18625461, -1.33465937, -1.0230075 ,  0.        , -1.05119428,
       -1.01777476, -1.04544227,  0.        , -1.0575755 , -1.15348943,
       -1.02035816,  0.        , -1.02101811, -1.02000198,  0.        ,
        0.        , -1.5346928 ,  0.        , -1.03552764, -1.02185964,
       -1.0717382 , -1.03934675, -1.12859054, -1.06351254, -1.0227711 ,
       -1.04812184,  0.        ,  0.        , -1.57570573,  0.        ,
       -1.02209068, -1.05211264,  0.        , -1.02395501,  0.        ,
       -1.26098759, -1.02972352, -6.36968085,  0.        , -1.02577556,
       -1.02416951, -1.04164862, -1.030732  , -1.02196284, -1.06058333,
       -1.02556084, -1.01718386,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        , -1.01727472, -1.04342869, -1.02041601,
       -1.0215636 ,  0.        , -1.02281975,  0.        , -1.07

In [ ]:
type(km_media)

numpy.ndarray

Declaraçao de Variavel


In [ ]:
ano_atual = 2022
ano_fabricacao = 2008
km_total = 129000.48

In [ ]:
ano_atual

2022

In [ ]:
km_total / (ano_atual - ano_fabricacao)

9214.32

In [ ]:
km_media = km_total / (ano_atual - ano_fabricacao)

In [ ]:
km_media

9214.32

## **Declaraçao de Variavel multipla**

In [ ]:
ano_atual, ano_fabricacao, km_total = 2022, 2008, 129000.12

In [ ]:
ano_atual

2022

In [ ]:
ano_atual, ano_fabricacao, km_total = 2022, 2008, 129000.12
km_media = km_total / (ano_atual -  ano_fabricacao)
km_media

9214.294285714286

In [ ]:
 zero_km = True
 zero_km = False 

In [ ]:
zero_km = bool 
zero_km

bool

In [ ]:
text = 'A quilometragem média do veículo é '
Km = 100000
Ano_atual = 2019
Ano_fabricacao = 1999

In [ ]:
text + str( int( Km / (Ano_atual - Ano_fabricacao) ) ) + ' km' #Aqui convertemos de string para inteiro

'A quilometragem média do veículo é 5000 km'

In [ ]:
print('Olá, {}! Este é seu acesso de numero {}'.format('Jorge Diego', 32))

Olá, Jorge Diego! Este é seu acesso de numero 32


# **Lista com tipos de dados** **variados** 

In [2]:
carros_um = ['carros-anos.txt']
carros_um

['carros-anos.txt']

In [3]:
carro = [
    'Jetta Variant', 
    'Motor 4.0 Turbo', 
    2003, 
    44410.0, 
    False, 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 
    88078.64
]

In [5]:
carro

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
 88078.64]

In [6]:
'2003' in carro

False

In [7]:
'Rodas de liga' in carro

False

In [8]:
'False' not in carro

True

In [11]:
letras = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
letras


['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']

In [12]:
letras[1:2]

['B']

In [18]:
letras[-3:]

['F', 'G', 'H']

In [20]:
carros = [
    [
        'Jetta Variant',
        'Motor 4.0 Turbo',
        2003,
        False,
        ['Rodas de liga', 'Travas elétricas', 'Piloto automático']
    ],
    [
        'Passat',
        'Motor Diesel',
        1991,
        True,
        ['Central multimídia', 'Teto panorâmico', 'Freios ABS']
    ]
]
carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático']],
 ['Passat',
  'Motor Diesel',
  1991,
  True,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS']]]

In [27]:
carros[0][-1]

['Rodas de liga', 'Travas elétricas', 'Piloto automático']

In [42]:
Acessorios = [
    'Rodas de liga', 
    'Travas elétricas', 
    'Piloto automático',
    'Bancos de couro',
    'Ar condicionado'
]

In [30]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado']

In [31]:
Acessorios.append('Airbag')
Acessorios.append('Vidros elétricos')
Acessorios.sort()
Acessorios.pop()
Acessorios

['Airbag',
 'Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Travas elétricas']

In [32]:
Acessorios.append('Airbag')
Acessorios.sort()
Acessorios.append('Vidros elétricos')
Acessorios.pop()
Acessorios

['Airbag',
 'Airbag',
 'Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Travas elétricas']

In [33]:
Acessorios.sort()
Acessorios.append('Airbag')
Acessorios.pop()
Acessorios.append('Vidros elétricos')
Acessorios

['Airbag',
 'Airbag',
 'Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Travas elétricas',
 'Vidros elétricos']

In [34]:
Acessorios.append('Airbag')
Acessorios.sort()
Acessorios.pop()
Acessorios.append('Vidros elétricos')
Acessorios

['Airbag',
 'Airbag',
 'Airbag',
 'Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Travas elétricas',
 'Vidros elétricos']

In [35]:
Acessorios.append('Airbag')
Acessorios.append('Vidros elétricos')
Acessorios.sort()
Acessorios.pop()
Acessorios

['Airbag',
 'Airbag',
 'Airbag',
 'Airbag',
 'Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Travas elétricas',
 'Vidros elétricos']

In [40]:
dados = [1, 2, 3, 4]
dados_copia = dados
dados_copia.append(5)
dados
dados_copia
dados

[1, 2, 3, 4, 5]

In [41]:
Acessorios

['Airbag',
 'Airbag',
 'Airbag',
 'Airbag',
 'Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Travas elétricas',
 'Vidros elétricos']

In [43]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado']

## **Trabalhnado com For**

In [44]:
for item in Acessorios:
  print(item)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado


In [45]:
quadrado = []
for i in range(10):
  quadrado.append(i ** 2)

quadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [46]:
quadrado = []
quadrado.append(i ** 2) for i in range(10)

SyntaxError: ignored

In [49]:
[i ** 2 for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

## **Loop Aninhado**

In [50]:
dados = [ 
    ['A', 'B', 'C'],
    ['D', 'E', 'F'],
    ['G', 'H', 'I']
]

In [51]:
result = []
for lista in dados:
    for item in lista:
        result.append(item)
result

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

In [52]:
result_2 = []
for lista in dados:
    result_2 += lista
result_2

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

In [53]:
[item for lista in dados for item in lista]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

## **Instrução** **if** 

In [74]:
dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weeknd', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weeknd', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [68]:
for lista in dados:
  if(lista[2] == True):
    print(lista)

['DS5', 2019, True]
['A5', 2019, True]


IndexError: ignored

In [80]:
zero_km_Y = []
for lista in dados:
  if(lista[3] == False):
    zero_km_Y.append(lista)

zero_km_Y

IndexError: ignored

In [83]:
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weeknd', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [85]:
ano = 2003
if(ano == 2003):
  print('OK')

OK


In [1]:
import numpy as np

In [4]:
from numpy import orange

ImportError: ignored

In [6]:
km = np.loadtxt('carros-km.txt')

In [7]:
km

array([4.44100e+04, 5.71200e+03, 3.71230e+04, 0.00000e+00, 2.57570e+04,
       1.07280e+04, 0.00000e+00, 7.75990e+04, 9.91970e+04, 3.79780e+04,
       1.28590e+04, 8.05200e+03, 8.97730e+04, 0.00000e+00, 4.14570e+04,
       1.15607e+05, 4.64490e+04, 0.00000e+00, 3.70860e+04, 1.51730e+04,
       1.01193e+05, 0.00000e+00, 9.80790e+04, 1.02959e+05, 0.00000e+00,
       0.00000e+00, 5.79500e+03, 0.00000e+00, 5.88480e+04, 9.43810e+04,
       3.01630e+04, 5.33320e+04, 1.77200e+04, 3.38080e+04, 9.06840e+04,
       4.39750e+04, 0.00000e+00, 0.00000e+00, 5.52600e+03, 0.00000e+00,
       9.34150e+04, 4.07620e+04, 0.00000e+00, 8.63020e+04, 0.00000e+00,
       9.75500e+03, 6.99450e+04, 2.39500e+03, 0.00000e+00, 8.03490e+04,
       8.55540e+04, 5.04960e+04, 6.77160e+04, 9.39470e+04, 3.53450e+04,
       8.10070e+04, 1.19513e+05, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 1.18895e+05, 4.85090e+04, 1.00912e+05,
       9.56490e+04, 0.00000e+00, 9.04950e+04, 0.00000e+00, 2.913

In [17]:
peso = np.array([106.0, 68.5, 75.0])

In [12]:
altura = np.array([1.9, 1.53, 4.75])

In [20]:

IMC = peso/(altura *peso)
IMC

array([0.52631579, 0.65359477, 0.21052632])

In [21]:
peso = np.array([106.0, 68.5, 75.0])
altura = np.array([1.9, 1.53, 1.75])
IMC = peso / altura ** 2
IMC

array([29.36288089, 29.26224956, 24.48979592])

In [24]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
contador[1:5:2]

array([1, 3])

In [30]:
dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weeknd', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weeknd', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [31]:
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weeknd', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [39]:
dados[3::4]

[['DS5', 2019, True], ['Série 3 Cabrio', False]]

In [40]:
dados = np.array(
    [
        ['Roberto', 'casado', 'masculino'],
        ['Sheila', 'solteiro', 'feminino'],
        ['Bruno', 'solteiro', 'masculino'],
        ['Rita', 'casado', 'feminino']
    ]
)

In [45]:
dados[0::2,:2]

array([['Roberto', 'casado'],
       ['Bruno', 'solteiro']], dtype='<U9')

In [50]:
anos = 2008
km = 128000
info_carros = km + anos
info_carros

130008

In [52]:
anos = np.loadtxt(fname = 'carros-anos.txt', dtype = int)
km = np.loadtxt(fname = 'carros-km.txt')
valor = np.loadtxt(fname = 'carros-valor.txt')


In [53]:
anos

array([2003, 1991, 1990, 2019, 2006, 2012, 2019, 2009, 2010, 2011, 2002,
       2007, 2001, 2019, 2009, 2016, 2012, 2019, 2016, 2017, 2002, 2019,
       1994, 1991, 2019, 2019, 2016, 2019, 2002, 1991, 1997, 1995, 2018,
       1991, 2014, 1995, 2019, 2019, 2009, 2019, 2013, 2003, 2019, 2002,
       2019, 2002, 2004, 2001, 2019, 2003, 2009, 2006, 2000, 2006, 2010,
       1994, 2007, 2019, 2019, 2019, 2019, 2019, 2017, 2011, 2001, 1996,
       2019, 1994, 2019, 2007, 1994, 2007, 1997, 2006, 2013, 1994, 2008,
       2008, 2019, 2019, 1999, 2007, 1993, 1995, 2019, 2019, 2016, 2011,
       2019, 2002, 2013, 2017, 2016, 2008, 2018, 2003, 2003, 2004, 2010,
       2019, 2006, 2001, 2019, 2015, 2018, 2017, 1992, 2001, 1993, 1995,
       2003, 2014, 2008, 2013, 2019, 2017, 2019, 2019, 2006, 2015, 2007,
       2005, 2017, 1998, 2019, 1999, 2019, 2009, 2003, 1994, 2019, 1994,
       2019, 2015, 1996, 1997, 1993, 2019, 1992, 1995, 2019, 1990, 2019,
       2019, 1991, 1990, 2012, 2007, 2013, 2000, 20

In [54]:
km

array([4.44100e+04, 5.71200e+03, 3.71230e+04, 0.00000e+00, 2.57570e+04,
       1.07280e+04, 0.00000e+00, 7.75990e+04, 9.91970e+04, 3.79780e+04,
       1.28590e+04, 8.05200e+03, 8.97730e+04, 0.00000e+00, 4.14570e+04,
       1.15607e+05, 4.64490e+04, 0.00000e+00, 3.70860e+04, 1.51730e+04,
       1.01193e+05, 0.00000e+00, 9.80790e+04, 1.02959e+05, 0.00000e+00,
       0.00000e+00, 5.79500e+03, 0.00000e+00, 5.88480e+04, 9.43810e+04,
       3.01630e+04, 5.33320e+04, 1.77200e+04, 3.38080e+04, 9.06840e+04,
       4.39750e+04, 0.00000e+00, 0.00000e+00, 5.52600e+03, 0.00000e+00,
       9.34150e+04, 4.07620e+04, 0.00000e+00, 8.63020e+04, 0.00000e+00,
       9.75500e+03, 6.99450e+04, 2.39500e+03, 0.00000e+00, 8.03490e+04,
       8.55540e+04, 5.04960e+04, 6.77160e+04, 9.39470e+04, 3.53450e+04,
       8.10070e+04, 1.19513e+05, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 1.18895e+05, 4.85090e+04, 1.00912e+05,
       9.56490e+04, 0.00000e+00, 9.04950e+04, 0.00000e+00, 2.913

In [55]:
valor

array([ 88078.64, 106161.94,  72832.16, 124549.07,  92612.1 ,  97497.73,
        56445.2 , 112310.44, 120716.27,  76566.49,  71647.59,  73919.53,
       112732.99,  53183.38, 127488.42,  59910.4 ,  61118.59,  88552.39,
        62696.69, 101726.3 , 106147.38,  94564.4 , 133529.84, 125684.65,
       121596.21,  71367.1 ,  95347.75, 105432.84,  57045.27, 120432.7 ,
        70707.2 ,  69105.18,  59358.69,  65955.4 ,  60017.03, 118909.52,
        51606.59, 123281.87,  69770.18, 102609.54,  67997.19, 135235.29,
        86641.34, 136818.39, 117626.73,  56208.7 ,  84222.65,  90781.65,
        64701.1 , 126350.49, 148152.89, 132298.83, 137627.63,  80422.71,
        56373.99,  70846.03, 128694.23, 133329.19, 131961.43, 112033.27,
        81399.35,  97163.1 ,  66007.16, 128776.22, 142623.02, 136930.13,
        66526.61, 114154.87, 142392.75, 146716.91, 122485.68,  97951.03,
        78283.49,  83434.04,  77836.23,  60813.92,  91353.86, 116281.21,
       145197.7 ,  50742.1 ,  73033.53,  54332.87, 

In [56]:
#Shape mostra o tamanho
anos.shape

(258,)

In [58]:
dataset = np.column_stack((anos, km, valor))
dataset

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0190000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0190000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0190000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0190000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

# **np.mean() **#Retorna a media dos elementos do array ao longo do eixo especificado